version: '2'
services:
  tasking-manager-db:
    build: ./devops/docker/postgis
    image: tasking-manager-db
    container_name: tasking-manager-db
    env_file:
      - tmdb-vars.env
  tasking-manager:
    build: ./
    image: tasking-manager
    container_name: tasking-manager
    depends_on:
      - tasking-manager-db
    ports:
      - "8000:8000"
    env_file:
      - tm-vars.env